package com.wiseasy.openapi.request;

import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @Auther: liqie
 * @Date: 2024/2/29 16:40
 * @Description: Merchants call this API to query the verification status of Debicheck
 */
@Getter
@Setter
@ToString
public class DebicheckOrderQuerylRequest extends OpenApiRequest<DebicheckOrderQueryResponse> {

    // Specifies merchant NO assigned by payment gateway
    private String merchant_no;

    // You can get the terminal sn from the merchant platform if you have already added the terminal
    private String terminal_sn;

    // Contract reference number.
    // This field is required when ‘serial_no’ is not provided.When there are multiple records with the same contract reference number, only the last record will be returned
    private String contract_reference_number;

    // Debicheck verification record serial number, a unique identifier generated by the PayCloud platform
    // Example：DC1000000001
    // This field is required when ‘contract_reference_number’ is not provided.
    private String serial_no;

}
