package com.wiseasy.openapi.request;

import com.wiseasy.openapi.response.DebicheckOrderCancelResponse;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

/**
 * @Auther: liqie
 * @Date: 2024/2/29 16:40
 * @Description: The merchant calls this API and actively cancels the verification request
 */
@Getter
@Setter
@ToString
public class DebicheckOrderCancelRequest extends OpenApiRequest<DebicheckOrderCancelResponse> {

    // Specifies merchant NO assigned by payment gateway
    private String merchant_no;

    // You can get the terminal sn from the merchant platform if you have already added the terminal
    private String terminal_sn;

    // APP that processes messages on the terminal. Value range: WISECASHIER
    private String message_receiving_application;

    // Debicheck verification record serial number, a unique identifier generated by the PayCloud platform
    private String serial_no;

}
